#!/usr/bin/env php
<?php

/*
 * This file is part of the api.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

use Dotenv\Dotenv;
use yii\console\Application;

$isLocal = php_uname('n') !== 'api.plusarchive.com';

if ($isLocal) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
    defined('YII_ENV') or define('YII_ENV', 'dev');
}

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/vendor/yiisoft/yii2/Yii.php';

if ($isLocal) {
    $dotenv = Dotenv::createImmutable(__DIR__);
    $dotenv->load();
}

$config = require __DIR__.'/config/console.php';
$application = new Application($config);
exit($application->run());
